FROM node:lts AS development
WORKDIR /client
COPY package.json /client/package.json
COPY package-lock.json /client/package-lock.json
RUN npm install
COPY . /client

ENV PORT=3000

CMD ["npm", "start"]

FROM development AS build
RUN npm run build

FROM development AS dev-envs
RUN <<EOF
apt-get update
apt-get install -y --no-install-recommends git
EOF

RUN <<EOF
useradd -s /bin/bash -m vscode
groupadd docker
usermod -aG docker vscode
EOF

COPY --from=gloursdocker/docker / /
CMD ["npm", "start"]

#setup for nginx

FROM nginx:alpine

COPY --from=build /client/default.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY --from=build /client/build .

ENTRYPOINT ["nginx", "-g", "daemon off;"]