version: '3.8'
services:  
  postgres_db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-gravesearch}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-Z17O14Kl$H3!}
    volumes:
      - pgdata1:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gravesearch"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  server:    
    build: ./server
    container_name: server   
    ports:      
      - '8080:80'    
    volumes:     
      - ./server:/index
    stdin_open: true
    tty: true
  client:
    build: ./client
    container_name: client
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ./client:/index
      - /etc/letsencrypt/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem
      - /etc/letsencrypt/ssl/options-ssl-nginx.conf:/etc/nginx/ssl/options-ssl-nginx.conf
      - /etc/letsencrypt/ssl/ssl-dhparams.pem:/etc/nginx/ssl/ssl-dhparams.pem
volumes:
  pgdata1: {}


